version: '3'
services:
  web:
    build: tests/.
    network_mode: host
    volumes:
      - "$PWD/tests:/app"
    command: npm install
    working_dir: /app

  selenoid-cm:
    image: "aerokube/cm:latest-release"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config:/root/.aerokube/selenoid"
    environment:
      OVERRIDE_HOME: "$PWD/config/"
    command: ["selenoid", "configure", "--vnc", "--tmpfs", "128"]

  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/opt:/opt/selenoid/video"
      - "$PWD/opt:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/opt"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4445:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    ports:
      - "8888:8080"